"""
Typed models representing every generated artifact during a migration.
Provides strict Pydantic structures for serialization and tracking.
"""
from datetime import datetime, timezone
from typing import Dict, Any, List, Union
from pydantic import BaseModel, Field

class BaseArtifact(BaseModel):
    """Base model enforcing required fields for all artifacts."""
    name: str = Field(description="Name or identifier of the artifact")
    path: str = Field(description="File system path or logical path where it should be saved")
    language: str = Field(default="unknown", description="Associated programming language or format")
    content: str = Field(default="", description="String content of the artifact")
    checksum: str = Field(default="", description="SHA-256 hash of the content for integrity")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp of generation")
    source: str = Field(description="Source agent or process that generated this artifact (e.g., CodeGeneratorAgent)")
    status: str = Field(default="pending", description="Lifecycle status (e.g., pending, approved, rejected, failed)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extensible dictionary for arbitrary metadata")

class GeneratedFile(BaseArtifact):
    """Represents a completely new file generated by an agent."""
    artifact_type: str = Field(default="generated_file", frozen=True)

class ModifiedFile(BaseArtifact):
    """Represents a pre-existing file that has been modified."""
    artifact_type: str = Field(default="modified_file", frozen=True)
    original_content: str = Field(default="", description="The content before modification")
    diff: str = Field(default="", description="The patch/diff of the modification")

class DeletedFile(BaseArtifact):
    """Represents a file marked for deletion in the target ERP."""
    artifact_type: str = Field(default="deleted_file", frozen=True)

class ReviewReport(BaseArtifact):
    """A report generated by a reviewer agent critiquing code."""
    artifact_type: str = Field(default="review_report", frozen=True)
    passed: bool = Field(default=False, description="Whether the code passed the review")
    feedback: List[str] = Field(default_factory=list, description="Specific action items or flaws found")

class ValidationReport(BaseArtifact):
    """A report generated by tests or static analysis tools (e.g., Pytest, Alembic)."""
    artifact_type: str = Field(default="validation_report", frozen=True)
    tests_run: int = Field(default=0, description="Total tests executed")
    tests_passed: int = Field(default=0, description="Tests passed successfully")
    errors: List[str] = Field(default_factory=list, description="Tracebacks or error messages")

class MigrationArtifact(BaseModel):
    """Aggregates all individual files and reports for a single migration unit."""
    migration_id: str = Field(description="Unique run ID for the migration")
    files: List[Union[GeneratedFile, ModifiedFile, DeletedFile]] = Field(default_factory=list)
    reviews: List[ReviewReport] = Field(default_factory=list)
    validations: List[ValidationReport] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class MigrationResult(BaseModel):
    """The final conclusive payload of a migration run."""
    migration_id: str
    success: bool = Field(description="Did the migration complete successfully and pass all tests?")
    artifacts: MigrationArtifact
    summary: str = Field(description="A human-readable summary of the run")
