"""
Strongly typed response models for LLM interactions.
"""
from typing import Optional, Any, Dict, List
from pydantic import BaseModel, Field

class TokenUsage(BaseModel):
    """Tracks token usage for a single LLM request."""
    prompt_tokens: int = Field(default=0, description="Tokens consumed by the prompt")
    completion_tokens: int = Field(default=0, description="Tokens generated by the model")
    total_tokens: int = Field(default=0, description="Total tokens used")

class PromptMetadata(BaseModel):
    """Metadata regarding the prompt template used."""
    template_name: Optional[str] = Field(default=None, description="Name of the Jinja template used")
    variables: Dict[str, Any] = Field(default_factory=dict, description="Variables injected into the template")

class CodeArtifact(BaseModel):
    """Represents a piece of extracted or generated code."""
    language: str = Field(description="Programming language (e.g., python, cpp, sql)")
    content: str = Field(description="The source code content extracted from the LLM")
    filename: Optional[str] = Field(default=None, description="Inferred or explicitly stated filename")

class MigrationArtifact(BaseModel):
    """A higher-level artifact output containing migration results (like a full module)."""
    artifact_type: str = Field(description="Type of artifact (e.g., sqlalchemy_model, pydantic_schema)")
    artifacts: List[CodeArtifact] = Field(default_factory=list, description="List of generated code artifacts")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Any additional metadata regarding the migration")

class LLMResponse(BaseModel):
    """Standardized response from the LLM client."""
    text: str = Field(description="Raw text response from the model")
    structured_output: Optional[Any] = Field(default=None, description="Parsed Pydantic model if structured generation was used")
    usage: TokenUsage = Field(default_factory=TokenUsage, description="Token usage statistics")
    latency_ms: float = Field(default=0.0, description="Time taken to generate the response in milliseconds")
    finish_reason: Optional[str] = Field(default=None, description="Reason the model stopped generating (e.g., stop, length)")
